Testing Github Actions CICD

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -26,11 +26,16 @@ jobs:
         run: dotnet build API.sln --configuration Debug --no-restore
 
       - name: Run Tests with Coverage
-        run: dotnet test API.sln --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/Coverage/coverage.cobertura.xml /p:Threshold=80 /p:ThresholdType=line /p:ThresholdType=branch /p:Exclude="[API]*Program.cs" /p:ExcludeByFile="**/RedisSettings.cs"
+        run: dotnet test API.sln --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/coverage.cobertura.xml /p:Threshold=80 /p:ThresholdType=line /p:Exclude="[API]*Program.cs" /p:ExcludeByFile="**/RedisSettings.cs"
 
       - name: Verify Test Coverage
         run: |
-          COVERAGE=$(grep -oP '(?<=<coverage line-rate=")[0-9.]+' TestResults/Coverage/coverage.cobertura.xml)
+          COVERAGE_FILE=$(find Tests/API.Tests/TestResults -name "coverage.cobertura.xml" | head -n 1)
+          if [ -z "$COVERAGE_FILE" ]; then
+            echo "Coverage file not found. Failing build."
+            exit 1
+          fi
+          COVERAGE=$(grep -oP '(?<=<coverage line-rate=")[0-9.]+' "$COVERAGE_FILE")
           if (( $(echo "$COVERAGE < 0.8" | bc -l) )); then
             echo "Test coverage ($COVERAGE) is below 80%. Failing the build."
             exit 1
